### ISSUE TITLE
JVM metrics

### ISSUE THREAD

**Issue by dwybourn** [alphagov/paas-prometheus-exporter#27]
Hi

Would it be possible to get jvm metrics included? Or would we be better of using something else for these metrics?

Thanks
David

**Comment by richardTowers** [comment]
Hi @dwybourn,

I think we'd want to leave jvm metrics to the application itself (i.e. have the application report them on its own `/metrics` endpoint and have prometheus scrape that).

This exporter mostly looks at things that are common to all applications (like CPU), and can therefore be tracked inside the cloud foundry platform. By default I don't think we get anything for JVM applications.

**Comment by dwybourn** [comment]
Thanks, we'll do that then.
