### ISSUE TITLE
Requests metrics do not include internal app-to-app requests

### ISSUE THREAD

**Issue by 46bit** [alphagov/paas-prometheus-exporter#28]
I don't know much about this codebase, but for counting requests it seems to be using the `requests.xxx` metrics from Gorouter (https://docs.cloudfoundry.org/running/all_metrics.html#gorouter.)

A tenant discovered this codebase's request metrics do not include internal app-to-app requests because those don't go through the Gorouter.

I don't think there is a readily-available place we can get metrics for internal requests from. But we might be able to provide something for it (e.g., a route service, if route services even work for internal app-to-app requests?)

**Comment by richardTowers** [comment]
Might be fixable once Envoy / Istio lands 🤔

**Comment by philandstuff** [comment]
A lot of conversations we had last year about this and paas-metric-exporter ended with

> Might be fixable once Envoy / Istio lands 🤔

**Comment by tlwr** [comment]
So much so that `cf-networking` have a label for this 😆 https://github.com/cloudfoundry/gorouter/issues?q=is%3Aissue+is%3Aopen+label%3Awill-fix-with-envoy

**Comment by 46bit** [comment]
This is probably not possible right now without doing Work. It might make sense to name the metric `external_requests.xxx` to indicate this… but too late.
